import { Box, Button, Chip, Divider, Stack, Typography } from '@mui/material';
import { FiArrowLeft, FiEdit2, FiTrash2 } from 'react-icons/fi';
import { useNavigate, useParams } from 'react-router-dom';
import { useState } from 'react';
import { toast } from 'react-toastify';
import PageHeader from '../../../components/admin/common/PageHeader';
import AdminModal from '../../../components/admin/common/AdminModal';
import { StudentLoader } from '../../../components/admin/common/StudentStates';
import { useStudents } from '../../../context/StudentsContext';

const DetailSection = ({ title, children }) => <Box><Typography sx={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, color: '#1E293B', mb: 2 }}>{title}</Typography><div className="row g-3">{children}</div></Box>;
const Item = ({ label, value }) => <div className="col-12 col-sm-6 col-lg-4"><Typography sx={{ color: '#94A3B8', fontSize: '.75rem', textTransform: 'uppercase', fontWeight: 700 }}>{label}</Typography><Box sx={{ color: '#1E293B', fontFamily: 'Inter, sans-serif', mt: .5, wordBreak: 'break-word' }}>{value || '—'}</Box></div>;
const StudentDetails = () => { const { id } = useParams(); const navigate = useNavigate(); const { students, loading, deleteStudent } = useStudents(); const [confirming, setConfirming] = useState(false); const student = students.find((item) => item.id === id); if (loading) return <StudentLoader />; if (!student) return <Box><PageHeader title="Student not found" breadcrumbs={[{ label: 'Admin' }, { label: 'Students', to: '/admin/students' }, { label: 'Not found' }]} /><Button onClick={() => navigate('/admin/students')} startIcon={<FiArrowLeft />}>Back to Students</Button></Box>; const remove = () => { deleteStudent(id); toast.success('Student deleted.'); navigate('/admin/students'); }; return <Box><PageHeader title={`${student.firstName} ${student.lastName}`} subtitle={`Student ID: ${student.id}`} breadcrumbs={[{ label: 'Admin' }, { label: 'Students', to: '/admin/students' }, { label: `${student.firstName} ${student.lastName}` }]} action={<Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<FiEdit2 />} onClick={() => navigate(`/admin/students/${id}/edit`)}>Edit Student</Button><Button variant="contained" color="error" startIcon={<FiTrash2 />} onClick={() => setConfirming(true)}>Delete</Button></Stack>} /><Box sx={{ maxWidth: 960, p: { xs: 2, sm: 3 }, bgcolor: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px' }}><DetailSection title="Student Information"><Item label="Student ID" value={student.id} /><Item label="Name" value={`${student.firstName} ${student.lastName}`} /><Item label="Date of Birth" value={student.dateOfBirth} /><Item label="Gender" value={student.gender} /><div className="col-12 col-sm-6 col-lg-4"><Typography sx={{ color: '#94A3B8', fontSize: '.75rem', textTransform: 'uppercase', fontWeight: 700 }}>Status</Typography><Chip label={student.status} size="small" color={student.status === 'Active' ? 'success' : 'default'} sx={{ mt: .5 }} /></div></DetailSection><Divider sx={{ my: 3 }} /><DetailSection title="Contact Information"><Item label="Email" value={student.email} /><Item label="Phone" value={student.phone} /><Item label="Address" value={student.address} /></DetailSection><Divider sx={{ my: 3 }} /><DetailSection title="Academic Information"><Item label="Class" value={student.class} /><Item label="Section" value={student.section} /><Item label="Admission Date" value={student.admissionDate} /></DetailSection><Divider sx={{ my: 3 }} /><DetailSection title="Parent / Guardian Information"><Item label="Name" value={student.parentName} /><Item label="Phone" value={student.parentPhone} /></DetailSection><Button sx={{ mt: 3 }} startIcon={<FiArrowLeft />} onClick={() => navigate('/admin/students')}>Back to Students</Button></Box><AdminModal open={confirming} onClose={() => setConfirming(false)} onConfirm={remove} title="Delete student" message={`Are you sure you want to delete ${student.firstName} ${student.lastName}? This cannot be undone.`} confirmLabel="Delete" /></Box>; };
export default StudentDetails;
