import { Button, FormControl, InputLabel, MenuItem, OutlinedInput, Select, Stack, TextField, Typography } from '@mui/material';
import { Controller, useForm } from 'react-hook-form';
import { FiSave } from 'react-icons/fi';
import { STUDENT_CLASSES } from '../../../data/students';

const fieldSx = { '& .MuiOutlinedInput-root': { borderRadius: '10px', fontFamily: 'Inter, sans-serif', '& fieldset': { borderColor: '#E2E8F0' }, '&.Mui-focused fieldset': { borderColor: '#2563EB' } }, '& .MuiInputLabel-root': { fontFamily: 'Inter, sans-serif' } };
const initialValues = { firstName: '', lastName: '', dateOfBirth: '', gender: '', email: '', phone: '', address: '', class: '', section: '', admissionDate: '', parentName: '', parentPhone: '', status: 'Active' };
const SelectField = ({ name, label, values, control, errors, required = true }) => <Controller name={name} control={control} rules={required ? { required: `${label} is required` } : undefined} render={({ field }) => <FormControl fullWidth error={!!errors[name]} sx={fieldSx}><InputLabel>{label}{required ? ' *' : ''}</InputLabel><Select {...field} input={<OutlinedInput label={`${label}${required ? ' *' : ''}`} />}>{values.map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select>{errors[name] && <Typography variant="caption" color="error" sx={{ mt: .5 }}>{errors[name].message}</Typography>}</FormControl>} />;

const StudentForm = ({ student, onSubmit, onCancel, submitLabel }) => {
  const { register, handleSubmit, control, formState: { errors } } = useForm({ defaultValues: student || initialValues });
  const text = (name, label, options = {}) => <TextField key={name} label={`${label}${options.required === false ? '' : ' *'}`} type={options.type || 'text'} fullWidth multiline={options.multiline} rows={options.rows} {...register(name, options.rules || (options.required === false ? {} : { required: `${label} is required` }))} error={!!errors[name]} helperText={errors[name]?.message} sx={fieldSx} />;
  return <form onSubmit={handleSubmit(onSubmit)} noValidate><Stack spacing={3}>
    <section><Typography sx={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, mb: 2 }}>Personal Information</Typography><div className="row g-3"><div className="col-12 col-sm-6">{text('firstName', 'First Name')}</div><div className="col-12 col-sm-6">{text('lastName', 'Last Name')}</div><div className="col-12 col-sm-6">{text('dateOfBirth', 'Date of Birth', { type: 'date' })}</div><div className="col-12 col-sm-6"><SelectField name="gender" label="Gender" values={['Female', 'Male', 'Other']} control={control} errors={errors} /></div></div></section>
    <section><Typography sx={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, mb: 2 }}>Contact Information</Typography><Stack spacing={2}><div className="row g-3"><div className="col-12 col-sm-6">{text('email', 'Email', { rules: { required: 'Email is required', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Enter a valid email address' } } })}</div><div className="col-12 col-sm-6">{text('phone', 'Phone', { rules: { required: 'Phone is required', pattern: { value: /^[0-9\s+()-]{7,20}$/, message: 'Enter a valid phone number' } } })}</div></div>{text('address', 'Address', { multiline: true, rows: 2 })}</Stack></section>
    <section><Typography sx={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, mb: 2 }}>Academic Information</Typography><div className="row g-3"><div className="col-12 col-sm-4"><SelectField name="class" label="Class / Grade" values={STUDENT_CLASSES} control={control} errors={errors} /></div><div className="col-12 col-sm-4">{text('section', 'Section')}</div><div className="col-12 col-sm-4">{text('admissionDate', 'Admission Date', { type: 'date' })}</div></div></section>
    <section><Typography sx={{ fontFamily: 'Inter, sans-serif', fontWeight: 700, mb: 2 }}>Parent / Guardian Information</Typography><div className="row g-3"><div className="col-12 col-sm-6">{text('parentName', 'Parent / Guardian Name')}</div><div className="col-12 col-sm-6">{text('parentPhone', 'Parent / Guardian Phone', { rules: { required: 'Parent phone is required', pattern: { value: /^[0-9\s+()-]{7,20}$/, message: 'Enter a valid phone number' } } })}</div></div></section>
    <SelectField name="status" label="Status" values={['Active', 'Inactive']} control={control} errors={errors} />
    <Stack direction="row" spacing={1.5}><Button variant="outlined" onClick={onCancel}>Cancel</Button><Button type="submit" variant="contained" startIcon={<FiSave />}>{submitLabel}</Button></Stack>
  </Stack></form>;
};
export default StudentForm;
